- src/main.ts
> add way to delete notes from Obsidian thru metadata & new sync type

- src/main.ts
> add button to get all links from Obsidian

- .gitignore
- src/main.ts
- src/settings.ts
- src/utils.ts
Regression tested everything except encryption since I don't have a key set up
Closes #17
> :reycle: formatted and refactored code into new files

- src/inputModal.ts
- src/main.ts
> convert same source to text containing & handle empty string

- src/main.ts
- src/settings.ts
- src/utils.ts
> :sparkles: fleeting notes tag filter when pulling notes #31

- src/main.ts
- src/settings.ts
- src/utils.ts
link issue [Feature Request] tags metadata  
Closes #29
> Tag-filter

- src/main.ts
- src/utils.ts
> fix bug with auto generating titles

- src/main.ts
- src/settings.ts
- src/utils.ts
> Fix unexpected logouts

- package-lock.json
- package.json
- src/main.ts
- src/settings.ts
- src/supabase_sync.ts
> add setting to sync obsidian links to fleeting notes

- src/file_system_sync.ts
- src/settings.ts
> add delete for two-way sync

- src/main.ts
- src/supabase_sync.ts
> add command to create empty note in fleeting notes

- src/file_system_sync.ts
- src/main.ts
Related to #73 only for (realtime two-way sync)
Closes #75
> prevent supabaseSync on creating notes when deleting them (realtime two-way sync)

- src/main.ts
- src/settings.ts
- src/supabase_sync.ts
- src/utils.ts
> add source metadata as a param in note template

- src/utils.ts
> fix tag regex and add additional escape for backslashes in yaml

- src/file_system_sync.ts
- src/settings.ts
- src/utils.ts
> add setting to adjust date format

- src/file_system_sync.ts
- src/utils.ts
> add source title as an option when auto generating title

- src/file_system_sync.ts
> files names will not be renamed during sync

- src/main.ts
> fix bug where sync creates duplicate files

- src/components/inputModal.ts
- src/file_system_sync.ts
- src/main.ts
- src/settings.ts
- src/supabase_sync.ts
- src/utils.ts
performed lint on save with eslint (i think)
> lint on save

- src/utils.ts
> fix yaml escape function by changing to global replace

- src/file_system_sync.ts
- src/main.ts
- src/settings.ts
- src/utils.ts
> add ability to adjust title template

- src/settings.ts
> restrict editing of note-template in two-way sync

- src/file_system_sync.ts
- Made `deleteNotes` function async in  file_system_sync.ts
Closes #121
> Fixed delete function

- src/main.test.js
- src/main.ts
- src/utils.ts
> Jest testing
